name: Latest blog post workflow
on:
  schedule: # 자동으로 업데이트할 시간 (5시간마다)
    - cron: '0 */5 * * *'
  workflow_dispatch: # 수동으로도 실행 가능하게 설정

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "[https://velog.io/@jh11240/rss](https://velog.io/@jh11240/rss)" # 예: https://velog.io/@username/rss
          template: "$newline - $date [ $title ]($url)"
